openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
  description: API for user registration, login, and profile management
servers:
  - url: http://localhost:5000
paths:
  /users/register:
    post:
      summary: Register a new user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                role:
                  type: string
              required:
                - username
                - email
                - password
                - role
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  userId:
                    type: string
        "400":
          description: User already registered
        "500":
          description: Error creating user

  /users/login:
    post:
      summary: Authenticate a user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        "200":
          description: User authenticated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
        "401":
          description: Invalid credentials
        "404":
          description: User not found
        "500":
          description: Error authenticating user

  /users/profile:
    get:
      summary: Get user profile
      tags:
        - Users
      responses:
        "200":
          description: User profile fetched successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: User not found
        "500":
          description: Error fetching user profile

components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
        username:
          type: string
        email:
          type: string
        role:
          type: string
      required:
        - _id
        - username
        - email
        - role
